'use client';

import { useMemo } from 'react';
import { useAppLocale } from '@/lib/locale';

export type DashboardLocale = 'en' | 'hi' | 'bn';

const dashboardCopy = {
  en: {
    shell: {
      brandTagline: 'Verify before you amplify',
      overview: 'Overview',
      fakeNewsDetector: 'Fake News Detector',
      deepfakeDetector: 'Deepfake Detector',
      scanHistory: 'Scan History',
      reports: 'Reports',
      settings: 'Settings',
      allScans: 'All Scans',
      adminPanel: 'Admin Panel',
      login: 'Login',
      logout: 'Logout',
      user: 'User',
      admin: 'Admin',
      signOut: 'Sign out',
    },
    overview: {
      metrics: [
        { label: 'Total scans', hint: 'Across news and media analysis' },
        { label: 'High-risk alerts', hint: 'Requires human review' },
        { label: 'Model health', hint: 'Weighted benchmark accuracy' },
        { label: 'Median confidence', hint: 'High quality predictions' },
      ],
      weeklyScanVolume: 'Weekly scan volume',
      liveDemoDataset: 'Live demo dataset',
      verdictSplit: 'Verdict split',
      snapshot30Days: '30-day snapshot',
      modelAccuracy: 'Model accuracy',
      benchmarkSnapshot: 'Benchmark snapshot',
    },
    scan: {
      fakeNewsDetector: 'Fake News Detector',
      deepfakeDetector: 'Deepfake Detector',
      analyzeText: 'Analyze text, posts, forwarded messages, or URLs',
      inspectUploads: 'Inspect image, video, and audio uploads',
      language: 'Language',
      scanning: 'Scanning...',
      runFakeNewsScan: 'Run Fake News Scan',
      runDeepfakeScan: 'Run Deepfake Scan',
      output: 'Output',
      analysis: 'Analysis',
      verdict: 'Verdict',
      riskScore: 'Risk score',
      headline: 'Headline',
      articlePlaceholder: 'Paste article text or forwarded message',
      sourceUrl: 'Source URL',
      dropFile: 'Drop file here or click to upload',
      preview: 'Preview',
      clear: 'Clear',
      uploadType: 'Upload type',
      image: 'Image',
      video: 'Video',
      audio: 'Audio',
      selectedModeError: (mode: string, fileType: string) => `Selected mode is ${mode}, but uploaded file is ${fileType}`,
      fileTooLarge: (sizeMb: string) => `File size exceeds 100MB limit. File: ${sizeMb}MB`,
      largeFileWarning: (sizeMb: string) => `Large file (${sizeMb}MB) - scan may take longer.`,
      realFake: 'Real / Fake',
      probability: 'Probability',
      frameScore: 'Frame-by-frame suspicious score',
      waveformHints: 'Audio waveform / region hints',
      placeholderText: 'Your scan output appears here with confidence, risk meter, and explainable AI reasons. Similar verified links are surfaced for cross-checking.',
      highlightedRegions: 'Highlighted regions, frame scoring, and audio spectrogram insights will appear here after upload.',
    },
    history: {
      title: 'History',
      subtitle: 'Previous scans',
      searchPlaceholder: 'Search scans',
      noItems: 'No scans found yet.',
    },
    reports: {
      title: 'Reports',
      subtitle: 'Export scans as PDF',
      selectedCount: (count: number) => `${count} scan${count > 1 ? 's' : ''} selected`,
      generatePdf: 'Generate PDF',
      shareBundle: 'Share evidence bundle',
      copied: '✓ Copied to clipboard',
      selectAtLeastOne: 'Select at least one scan to share.',
      generated: 'Generated',
      scansIncluded: 'Scans included',
      all: 'All',
      fakeNews: 'Fake News',
      deepfake: 'Deepfake',
      deselectAll: 'Deselect all',
      selectAll: 'Select all',
      loading: 'Loading scans…',
      noScans: 'No scans found.',
      includedHeading: 'Included in report',
      includedItems: [
        'Scan metadata and source URL',
        'Flagged phrases and media anomalies',
        'Model confidence and risk scores',
        'Verdict label and audit trail',
        'Recommended next verification steps',
      ],
    },
    settings: {
      title: 'Settings',
      subtitle: 'Account & Preferences',
      profile: 'Profile',
      security: 'Security',
      scanPreferences: 'Scan Preferences',
      notifications: 'Notifications',
      dangerZone: 'Danger Zone',
      personalInformation: 'Personal information',
      memberSince: 'Member since',
      emailLocked: 'Email cannot be changed after registration.',
      saveProfile: 'Save Profile',
      saving: 'Saving…',
      currentPassword: 'Current Password',
      newPassword: 'New Password',
      confirmPassword: 'Confirm New Password',
      updatePassword: 'Update Password',
      updating: 'Updating…',
      defaultScanType: 'Default Scan Type',
      defaultLanguage: 'Default Language',
      riskThreshold: 'Risk Alert Threshold',
      autoSaveHistory: 'Auto-save scan history',
      showAiExplanations: 'Show AI explanations',
      savePreferences: 'Save Preferences',
      alertPreferences: 'Alert preferences',
      highRiskAlerts: 'High-risk scan alerts',
      scanCompleteNotifications: 'Scan complete notifications',
      weeklyDigest: 'Weekly digest',
      adminSystemAlerts: 'Admin system alerts',
      saveNotifications: 'Save Notifications',
      destructiveActions: 'Destructive actions',
      clearScanHistory: 'Clear scan history',
      resetPreferences: 'Reset preferences',
      signOutAllSessions: 'Sign out of all sessions',
      clearCache: 'Clear cache',
      reset: 'Reset',
      signOut: 'Sign out',
      sessionInfo: 'Session info',
      accountId: 'Account ID',
      role: 'Role',
      locale: 'Locale',
      token: 'Token',
      standardAccount: 'Standard account',
      adminAccount: 'Admin account',
      emailLabel: 'Email',
      fullNameLabel: 'Full Name',
      languageLabel: 'Language',
      systemInfo: 'Authentication info',
      jwtExpiry: 'JWT session expiry',
      rateLimiting: 'Rate limiting',
      uploadValidation: 'Upload validation',
      corsPolicy: 'CORS policy',
      passwordHashing: 'Password hashing',
      settingsHeader: 'Account & Preferences',
      manageSubtitle: 'Manage your profile, security, scan defaults, and notifications.',
    },
    admin: {
      users: 'Users',
      scans: 'Scans',
      fakeNews: 'Fake News',
      deepfake: 'Deepfake',
      modelStats: 'Model Stats',
      allUsers: 'All Users',
      modelAccuracyStats: 'Model accuracy stats',
      recentActivity: 'Recent activity',
      registeredUsers: 'Registered users',
      accountCount: (count: number) => `${count} account${count !== 1 ? 's' : ''} in MongoDB`,
      adminAccessRequired: 'Admin access required',
      signInAsAdmin: 'Sign in with an admin account to view this panel.',
      usersInMongo: 'users in MongoDB',
    },
  },
  hi: {
    shell: {
      brandTagline: 'प्रचार करने से पहले सत्यापित करें',
      overview: 'सारांश',
      fakeNewsDetector: 'फेक न्यूज़ डिटेक्टर',
      deepfakeDetector: 'डीपफेक डिटेक्टर',
      scanHistory: 'स्कैन इतिहास',
      reports: 'रिपोर्ट',
      settings: 'सेटिंग्स',
      allScans: 'सभी स्कैन',
      adminPanel: 'एडमिन पैनल',
      login: 'लॉगिन',
      logout: 'लॉगआउट',
      user: 'उपयोगकर्ता',
      admin: 'एडमिन',
      signOut: 'साइन आउट',
    },
    overview: {
      metrics: [
        { label: 'कुल स्कैन', hint: 'समाचार और मीडिया विश्लेषण के साथ' },
        { label: 'उच्च-जोखिम अलर्ट', hint: 'मानवीय समीक्षा आवश्यक' },
        { label: 'मॉडल स्वास्थ्य', hint: 'वेटेड बेंचमार्क सटीकता' },
        { label: 'मध्य विश्वास', hint: 'उच्च गुणवत्ता भविष्यवाणियाँ' },
      ],
      weeklyScanVolume: 'साप्ताहिक स्कैन मात्रा',
      liveDemoDataset: 'लाइव डेमो डेटा',
      verdictSplit: 'निर्णय विभाजन',
      snapshot30Days: '30-दिन का स्नैपशॉट',
      modelAccuracy: 'मॉडल सटीकता',
      benchmarkSnapshot: 'बेंचमार्क स्नैपशॉट',
    },
    scan: {
      fakeNewsDetector: 'फेक न्यूज़ डिटेक्टर',
      deepfakeDetector: 'डीपफेक डिटेक्टर',
      analyzeText: 'टेक्स्ट, पोस्ट, फॉरवर्ड संदेश या URL का विश्लेषण करें',
      inspectUploads: 'छवि, वीडियो और ऑडियो अपलोड की जांच करें',
      language: 'भाषा',
      scanning: 'स्कैन हो रहा है...',
      runFakeNewsScan: 'फेक न्यूज़ स्कैन चलाएँ',
      runDeepfakeScan: 'डीपफेक स्कैन चलाएँ',
      output: 'आउटपुट',
      analysis: 'विश्लेषण',
      verdict: 'निष्कर्ष',
      riskScore: 'जोखिम स्कोर',
      headline: 'शीर्षक',
      articlePlaceholder: 'लेख का पाठ या फॉरवर्ड किया गया संदेश चिपकाएँ',
      sourceUrl: 'स्रोत URL',
      dropFile: 'फ़ाइल यहाँ छोड़ें या अपलोड करने के लिए क्लिक करें',
      preview: 'पूर्वावलोकन',
      clear: 'हटाएँ',
      uploadType: 'अपलोड प्रकार',
      image: 'छवि',
      video: 'वीडियो',
      audio: 'ऑडियो',
      selectedModeError: (mode: string, fileType: string) => `चयनित मोड ${mode} है, लेकिन अपलोड की गई फ़ाइल ${fileType} है`,
      fileTooLarge: (sizeMb: string) => `फ़ाइल आकार 100MB सीमा से अधिक है। फ़ाइल: ${sizeMb}MB`,
      largeFileWarning: (sizeMb: string) => `बड़ी फ़ाइल (${sizeMb}MB) - स्कैन में अधिक समय लग सकता है।`,
      realFake: 'वास्तविक / नकली',
      probability: 'संभावना',
      frameScore: 'फ्रेम-वार संदिग्ध स्कोर',
      waveformHints: 'ऑडियो वेवफ़ॉर्म / क्षेत्र संकेत',
      placeholderText: 'स्कैन का आउटपुट यहाँ विश्वास, जोखिम मीटर और समझाने योग्य AI कारणों के साथ दिखाई देगा। क्रॉस-चेक के लिए समान सत्यापित लिंक दिखाए जाएंगे।',
      highlightedRegions: 'अपलोड के बाद हाइलाइट किए गए क्षेत्र, फ्रेम स्कोरिंग और ऑडियो स्पेक्ट्रोग्राम अंतर्दृष्टि यहाँ दिखाई देंगी।',
    },
    history: {
      title: 'इतिहास',
      subtitle: 'पिछले स्कैन',
      searchPlaceholder: 'स्कैन खोजें',
      noItems: 'अभी तक कोई स्कैन नहीं मिला।',
    },
    reports: {
      title: 'रिपोर्ट',
      subtitle: 'स्कैन को PDF के रूप में निर्यात करें',
      selectedCount: (count: number) => `${count} स्कैन चयनित`,
      generatePdf: 'PDF बनाएँ',
      shareBundle: 'साक्ष्य बंडल साझा करें',
      copied: '✓ क्लिपबोर्ड पर कॉपी हो गया',
      selectAtLeastOne: 'साझा करने के लिए कम से कम एक स्कैन चुनें।',
      generated: 'तैयार किया गया',
      scansIncluded: 'शामिल स्कैन',
      all: 'सभी',
      fakeNews: 'फेक न्यूज़',
      deepfake: 'डीपफेक',
      deselectAll: 'सभी चयन हटाएँ',
      selectAll: 'सभी चुनें',
      loading: 'स्कैन लोड हो रहे हैं…',
      noScans: 'कोई स्कैन नहीं मिला।',
      includedHeading: 'रिपोर्ट में शामिल',
      includedItems: [
        'स्कैन मेटाडेटा और स्रोत URL',
        'चिह्नित वाक्यांश और मीडिया विसंगतियाँ',
        'मॉडल विश्वास और जोखिम स्कोर',
        'निर्णय लेबल और ऑडिट ट्रेल',
        'अगले सत्यापन के लिए सुझाव',
      ],
    },
    settings: {
      title: 'सेटिंग्स',
      subtitle: 'खाता और प्राथमिकताएँ',
      profile: 'प्रोफ़ाइल',
      security: 'सुरक्षा',
      scanPreferences: 'स्कैन प्राथमिकताएँ',
      notifications: 'सूचनाएँ',
      dangerZone: 'खतरनाक क्षेत्र',
      personalInformation: 'व्यक्तिगत जानकारी',
      memberSince: 'सदस्य बने',
      emailLocked: 'रजिस्ट्रेशन के बाद ईमेल बदला नहीं जा सकता।',
      saveProfile: 'प्रोफ़ाइल सहेजें',
      saving: 'सहेजा जा रहा है…',
      currentPassword: 'वर्तमान पासवर्ड',
      newPassword: 'नया पासवर्ड',
      confirmPassword: 'नया पासवर्ड पुष्टि करें',
      updatePassword: 'पासवर्ड अपडेट करें',
      updating: 'अपडेट हो रहा है…',
      defaultScanType: 'डिफ़ॉल्ट स्कैन प्रकार',
      defaultLanguage: 'डिफ़ॉल्ट भाषा',
      riskThreshold: 'जोखिम अलर्ट सीमा',
      autoSaveHistory: 'स्कैन इतिहास स्वतः सहेजें',
      showAiExplanations: 'AI स्पष्टीकरण दिखाएँ',
      savePreferences: 'प्राथमिकताएँ सहेजें',
      alertPreferences: 'अलर्ट प्राथमिकताएँ',
      highRiskAlerts: 'उच्च-जोखिम स्कैन अलर्ट',
      scanCompleteNotifications: 'स्कैन पूर्ण होने की सूचना',
      weeklyDigest: 'साप्ताहिक सारांश',
      adminSystemAlerts: 'एडमिन सिस्टम अलर्ट',
      saveNotifications: 'सूचनाएँ सहेजें',
      destructiveActions: 'विनाशकारी क्रियाएँ',
      clearScanHistory: 'स्कैन इतिहास साफ़ करें',
      resetPreferences: 'प्राथमिकताएँ रीसेट करें',
      signOutAllSessions: 'सभी सत्रों से साइन आउट करें',
      clearCache: 'कैश साफ़ करें',
      reset: 'रीसेट',
      signOut: 'साइन आउट',
      sessionInfo: 'सत्र जानकारी',
      accountId: 'खाता आईडी',
      role: 'भूमिका',
      locale: 'लोकेल',
      token: 'टोकन',
      standardAccount: 'मानक खाता',
      adminAccount: 'एडमिन खाता',
      emailLabel: 'ईमेल',
      fullNameLabel: 'पूरा नाम',
      languageLabel: 'भाषा',
      systemInfo: 'प्रमाणीकरण जानकारी',
      jwtExpiry: 'JWT सत्र समाप्ति',
      rateLimiting: 'रेट लिमिटिंग',
      uploadValidation: 'अपलोड सत्यापन',
      corsPolicy: 'CORS नीति',
      passwordHashing: 'पासवर्ड हैशिंग',
      settingsHeader: 'खाता और प्राथमिकताएँ',
      manageSubtitle: 'अपनी प्रोफ़ाइल, सुरक्षा, स्कैन डिफ़ॉल्ट और सूचनाएँ प्रबंधित करें।',
    },
    admin: {
      users: 'उपयोगकर्ता',
      scans: 'स्कैन',
      fakeNews: 'फेक न्यूज़',
      deepfake: 'डीपफेक',
      modelStats: 'मॉडल आँकड़े',
      allUsers: 'सभी उपयोगकर्ता',
      modelAccuracyStats: 'मॉडल सटीकता आँकड़े',
      recentActivity: 'हाल की गतिविधि',
      registeredUsers: 'पंजीकृत उपयोगकर्ता',
      accountCount: (count: number) => `MongoDB में ${count} खाता`,
      adminAccessRequired: 'एडमिन एक्सेस आवश्यक',
      signInAsAdmin: 'यह पैनल देखने के लिए एडमिन खाते से साइन इन करें।',
      usersInMongo: 'MongoDB में उपयोगकर्ता',
    },
  },
  bn: {
    shell: {
      brandTagline: 'প্রচার করার আগে যাচাই করুন',
      overview: 'সংক্ষিপ্ত বিবরণ',
      fakeNewsDetector: 'ফেক নিউজ ডিটেক্টর',
      deepfakeDetector: 'ডিপফেক ডিটেক্টর',
      scanHistory: 'স্ক্যান ইতিহাস',
      reports: 'রিপোর্ট',
      settings: 'সেটিংস',
      allScans: 'সব স্ক্যান',
      adminPanel: 'অ্যাডমিন প্যানেল',
      login: 'লগইন',
      logout: 'লগআউট',
      user: 'ব্যবহারকারী',
      admin: 'অ্যাডমিন',
      signOut: 'সাইন আউট',
    },
    overview: {
      metrics: [
        { label: 'মোট স্ক্যান', hint: 'সংবাদ ও মিডিয়া বিশ্লেষণ জুড়ে' },
        { label: 'উচ্চ-ঝুঁকির সতর্কতা', hint: 'মানবিক পর্যালোচনা প্রয়োজন' },
        { label: 'মডেল স্বাস্থ্য', hint: 'ওজনযুক্ত বেঞ্চমার্ক সঠিকতা' },
        { label: 'মধ্যম আস্থা', hint: 'উচ্চ মানের পূর্বাভাস' },
      ],
      weeklyScanVolume: 'সাপ্তাহিক স্ক্যান পরিমাণ',
      liveDemoDataset: 'লাইভ ডেমো ডেটাসেট',
      verdictSplit: 'রায় বিভাজন',
      snapshot30Days: '৩০ দিনের স্ন্যাপশট',
      modelAccuracy: 'মডেল সঠিকতা',
      benchmarkSnapshot: 'বেঞ্চমার্ক স্ন্যাপশট',
    },
    scan: {
      fakeNewsDetector: 'ফেক নিউজ ডিটেক্টর',
      deepfakeDetector: 'ডিপফেক ডিটেক্টর',
      analyzeText: 'টেক্সট, পোস্ট, ফরওয়ার্ড করা বার্তা বা URL বিশ্লেষণ করুন',
      inspectUploads: 'ছবি, ভিডিও এবং অডিও আপলোড পরীক্ষা করুন',
      language: 'ভাষা',
      scanning: 'স্ক্যান হচ্ছে...',
      runFakeNewsScan: 'ফেক নিউজ স্ক্যান চালান',
      runDeepfakeScan: 'ডিপফেক স্ক্যান চালান',
      output: 'আউটপুট',
      analysis: 'বিশ্লেষণ',
      verdict: 'সিদ্ধান্ত',
      riskScore: 'ঝুঁকি স্কোর',
      headline: 'শিরোনাম',
      articlePlaceholder: 'প্রবন্ধের লেখা বা ফরওয়ার্ড করা বার্তা পেস্ট করুন',
      sourceUrl: 'সোর্স URL',
      dropFile: 'এখানে ফাইল ছাড়ুন বা আপলোড করতে ক্লিক করুন',
      preview: 'প্রিভিউ',
      clear: 'মুছুন',
      uploadType: 'আপলোডের ধরন',
      image: 'ছবি',
      video: 'ভিডিও',
      audio: 'অডিও',
      selectedModeError: (mode: string, fileType: string) => `নির্বাচিত মোড ${mode}, কিন্তু আপলোড করা ফাইল ${fileType}`,
      fileTooLarge: (sizeMb: string) => `ফাইলের আকার 100MB সীমা ছাড়িয়েছে। ফাইল: ${sizeMb}MB`,
      largeFileWarning: (sizeMb: string) => `বড় ফাইল (${sizeMb}MB) - স্ক্যান করতে বেশি সময় লাগতে পারে।`,
      realFake: 'বাস্তব / ভুয়া',
      probability: 'সম্ভাবনা',
      frameScore: 'ফ্রেম-ভিত্তিক সন্দেহজনক স্কোর',
      waveformHints: 'অডিও ওয়েভফর্ম / অঞ্চল সংকেত',
      placeholderText: 'স্ক্যানের আউটপুট এখানে আস্থা, ঝুঁকি মিটার এবং ব্যাখ্যাযোগ্য AI কারণসহ দেখা যাবে। ক্রস-চেকের জন্য অনুরূপ যাচাইকৃত লিংক দেখানো হবে।',
      highlightedRegions: 'আপলোডের পরে হাইলাইট করা অঞ্চল, ফ্রেম স্কোরিং এবং অডিও স্পেক্ট্রোগ্রাম অন্তর্দৃষ্টি এখানে দেখা যাবে।',
    },
    history: {
      title: 'ইতিহাস',
      subtitle: 'পূর্ববর্তী স্ক্যান',
      searchPlaceholder: 'স্ক্যান খুঁজুন',
      noItems: 'এখনও কোনো স্ক্যান পাওয়া যায়নি।',
    },
    reports: {
      title: 'রিপোর্ট',
      subtitle: 'স্ক্যান PDF হিসেবে রপ্তানি করুন',
      selectedCount: (count: number) => `${count}টি স্ক্যান নির্বাচিত`,
      generatePdf: 'PDF তৈরি করুন',
      shareBundle: 'প্রমাণ bundle শেয়ার করুন',
      copied: '✓ ক্লিপবোর্ডে কপি হয়েছে',
      selectAtLeastOne: 'শেয়ার করার জন্য অন্তত একটি স্ক্যান নির্বাচন করুন।',
      generated: 'তৈরি হয়েছে',
      scansIncluded: 'অন্তর্ভুক্ত স্ক্যান',
      all: 'সব',
      fakeNews: 'ফেক নিউজ',
      deepfake: 'ডিপফেক',
      deselectAll: 'সব নির্বাচন বাতিল করুন',
      selectAll: 'সব নির্বাচন করুন',
      loading: 'স্ক্যান লোড হচ্ছে…',
      noScans: 'কোনো স্ক্যান পাওয়া যায়নি।',
      includedHeading: 'রিপোর্টে অন্তর্ভুক্ত',
      includedItems: [
        'স্ক্যান মেটাডেটা এবং সোর্স URL',
        'চিহ্নিত বাক্যাংশ এবং মিডিয়া অস্বাভাবিকতা',
        'মডেল আস্থা এবং ঝুঁকি স্কোর',
        'রায় লেবেল এবং অডিট ট্রেইল',
        'পরবর্তী যাচাইয়ের সুপারিশ',
      ],
    },
    settings: {
      title: 'সেটিংস',
      subtitle: 'অ্যাকাউন্ট ও পছন্দসমূহ',
      profile: 'প্রোফাইল',
      security: 'নিরাপত্তা',
      scanPreferences: 'স্ক্যান পছন্দসমূহ',
      notifications: 'নোটিফিকেশন',
      dangerZone: 'ঝুঁকিপূর্ণ অংশ',
      personalInformation: 'ব্যক্তিগত তথ্য',
      memberSince: 'সদস্য হয়েছেন',
      emailLocked: 'রেজিস্ট্রেশনের পরে ইমেল পরিবর্তন করা যায় না।',
      saveProfile: 'প্রোফাইল সংরক্ষণ করুন',
      saving: 'সংরক্ষণ করা হচ্ছে…',
      currentPassword: 'বর্তমান পাসওয়ার্ড',
      newPassword: 'নতুন পাসওয়ার্ড',
      confirmPassword: 'নতুন পাসওয়ার্ড নিশ্চিত করুন',
      updatePassword: 'পাসওয়ার্ড আপডেট করুন',
      updating: 'আপডেট হচ্ছে…',
      defaultScanType: 'ডিফল্ট স্ক্যান ধরন',
      defaultLanguage: 'ডিফল্ট ভাষা',
      riskThreshold: 'ঝুঁকি সতর্কতা সীমা',
      autoSaveHistory: 'স্ক্যান ইতিহাস স্বয়ংক্রিয়ভাবে সংরক্ষণ করুন',
      showAiExplanations: 'AI ব্যাখ্যা দেখান',
      savePreferences: 'পছন্দসমূহ সংরক্ষণ করুন',
      alertPreferences: 'সতর্কতা পছন্দসমূহ',
      highRiskAlerts: 'উচ্চ-ঝুঁকির স্ক্যান সতর্কতা',
      scanCompleteNotifications: 'স্ক্যান সম্পন্ন হওয়ার নোটিফিকেশন',
      weeklyDigest: 'সাপ্তাহিক সারাংশ',
      adminSystemAlerts: 'অ্যাডমিন সিস্টেম সতর্কতা',
      saveNotifications: 'নোটিফিকেশন সংরক্ষণ করুন',
      destructiveActions: 'বিনাশকারী কার্যক্রম',
      clearScanHistory: 'স্ক্যান ইতিহাস মুছুন',
      resetPreferences: 'পছন্দসমূহ রিসেট করুন',
      signOutAllSessions: 'সব সেশন থেকে সাইন আউট করুন',
      clearCache: 'ক্যাশ পরিষ্কার করুন',
      reset: 'রিসেট',
      signOut: 'সাইন আউট',
      sessionInfo: 'সেশন তথ্য',
      accountId: 'অ্যাকাউন্ট আইডি',
      role: 'ভূমিকা',
      locale: 'লোকেল',
      token: 'টোকেন',
      standardAccount: 'স্ট্যান্ডার্ড অ্যাকাউন্ট',
      adminAccount: 'অ্যাডমিন অ্যাকাউন্ট',
      emailLabel: 'ইমেল',
      fullNameLabel: 'পূর্ণ নাম',
      languageLabel: 'ভাষা',
      systemInfo: 'প্রমাণীকরণ তথ্য',
      jwtExpiry: 'JWT সেশন মেয়াদ',
      rateLimiting: 'রেট লিমিটিং',
      uploadValidation: 'আপলোড যাচাই',
      corsPolicy: 'CORS নীতি',
      passwordHashing: 'পাসওয়ার্ড হ্যাশিং',
      settingsHeader: 'অ্যাকাউন্ট ও পছন্দসমূহ',
      manageSubtitle: 'আপনার প্রোফাইল, নিরাপত্তা, স্ক্যান ডিফল্ট এবং নোটিফিকেশন পরিচালনা করুন।',
    },
    admin: {
      users: 'ব্যবহারকারী',
      scans: 'স্ক্যান',
      fakeNews: 'ফেক নিউজ',
      deepfake: 'ডিপফেক',
      modelStats: 'মডেল পরিসংখ্যান',
      allUsers: 'সব ব্যবহারকারী',
      modelAccuracyStats: 'মডেল সঠিকতার পরিসংখ্যান',
      recentActivity: 'সাম্প্রতিক কার্যকলাপ',
      registeredUsers: 'নিবন্ধিত ব্যবহারকারী',
      accountCount: (count: number) => `MongoDB-তে ${count}টি অ্যাকাউন্ট`,
      adminAccessRequired: 'অ্যাডমিন অ্যাক্সেস প্রয়োজন',
      signInAsAdmin: 'এই প্যানেল দেখতে অ্যাডমিন অ্যাকাউন্ট দিয়ে সাইন ইন করুন।',
      usersInMongo: 'MongoDB-তে ব্যবহারকারী',
    },
  },
} as const;

export function useDashboardCopy() {
  const { locale } = useAppLocale();
  return useMemo(() => dashboardCopy[locale as DashboardLocale] ?? dashboardCopy.en, [locale]);
}
